"""initial schema

Revision ID: 0da7a4e98f61
Revises: 
Create Date: 2026-06-28 17:42:29.506006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0da7a4e98f61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macrociclo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_token_provider'), 'oauth_token', ['provider'], unique=True)
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hr_max_bpm', sa.Integer(), nullable=False),
    sa.Column('hr_rest_bpm', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('CARDIO', 'STRENGTH', name='workouttype'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('strength_total_volume_kg', sa.Float(), nullable=True),
    sa.Column('strength_total_sets', sa.Integer(), nullable=True),
    sa.Column('strength_exercises_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_external_id'), 'workout', ['external_id'], unique=True)
    op.create_table('cardio_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('gps_polyline', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avg_pace_s_per_km', sa.Float(), nullable=True),
    sa.Column('splits', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cardio_detail_workout_id'), 'cardio_detail', ['workout_id'], unique=True)
    op.create_table('mesociclo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('macrociclo_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('weekly_increment_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['macrociclo_id'], ['macrociclo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mesociclo_macrociclo_id'), 'mesociclo', ['macrociclo_id'], unique=False)
    op.create_table('strength_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strength_detail_workout_id'), 'strength_detail', ['workout_id'], unique=True)
    op.create_table('microciclo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mesociclo_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_deload', sa.Boolean(), nullable=False),
    sa.Column('base_load', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['mesociclo_id'], ['mesociclo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_microciclo_mesociclo_id'), 'microciclo', ['mesociclo_id'], unique=False)
    op.create_table('sesion_planificada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('microciclo_id', sa.Integer(), nullable=False),
    sa.Column('planned_type', sa.Enum('CARDIO', 'STRENGTH', name='workouttype'), nullable=False),
    sa.Column('planned_load', sa.Float(), nullable=False),
    sa.Column('planned_volume', sa.Float(), nullable=True),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['microciclo_id'], ['microciclo.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesion_planificada_microciclo_id'), 'sesion_planificada', ['microciclo_id'], unique=False)
    op.create_index(op.f('ix_sesion_planificada_workout_id'), 'sesion_planificada', ['workout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sesion_planificada_workout_id'), table_name='sesion_planificada')
    op.drop_index(op.f('ix_sesion_planificada_microciclo_id'), table_name='sesion_planificada')
    op.drop_table('sesion_planificada')
    op.drop_index(op.f('ix_microciclo_mesociclo_id'), table_name='microciclo')
    op.drop_table('microciclo')
    op.drop_index(op.f('ix_strength_detail_workout_id'), table_name='strength_detail')
    op.drop_table('strength_detail')
    op.drop_index(op.f('ix_mesociclo_macrociclo_id'), table_name='mesociclo')
    op.drop_table('mesociclo')
    op.drop_index(op.f('ix_cardio_detail_workout_id'), table_name='cardio_detail')
    op.drop_table('cardio_detail')
    op.drop_index(op.f('ix_workout_external_id'), table_name='workout')
    op.drop_table('workout')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_oauth_token_provider'), table_name='oauth_token')
    op.drop_table('oauth_token')
    op.drop_table('macrociclo')
    # ### end Alembic commands ###
